/* The following code was generated by JFlex 1.6.1 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2015  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */

package compilador;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/francisco/unlu/t1/compi/flex/java.flex</tt>
 */
public class Scanner implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\101\1\102\1\1\16\7\4\0\1\3\1\65"+
    "\1\21\1\0\1\6\1\71\1\66\1\22\1\51\1\52\1\5\1\70"+
    "\1\61\1\20\1\16\1\4\1\10\1\73\1\72\1\14\1\74\1\15"+
    "\1\77\1\75\1\76\1\11\1\60\1\57\1\64\1\62\1\63\2\0"+
    "\1\30\1\13\1\26\1\24\1\25\1\40\2\6\1\33\4\6\1\32"+
    "\3\6\1\31\3\6\1\27\1\6\1\12\2\6\1\55\1\23\1\56"+
    "\1\0\1\6\1\0\1\43\1\100\2\13\1\17\1\47\1\36\1\45"+
    "\1\46\2\6\1\41\1\6\1\34\1\42\2\6\1\37\1\50\1\35"+
    "\2\6\1\44\1\12\2\6\1\53\1\67\1\54\1\0\6\7\1\103"+
    "\32\7\2\0\4\6\4\0\1\6\2\0\1\7\7\0\1\6\4\0"+
    "\1\6\5\0\27\6\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0"+
    "\5\6\7\0\1\6\1\0\1\6\21\0\160\7\5\6\1\0\2\6"+
    "\2\0\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6"+
    "\1\0\123\6\1\0\213\6\1\0\5\7\2\0\236\6\11\0\46\6"+
    "\2\0\1\6\7\0\47\6\7\0\1\6\1\0\55\7\1\0\1\7"+
    "\1\0\2\7\1\0\2\7\1\0\1\7\10\0\33\6\5\0\3\6"+
    "\15\0\5\7\6\0\1\6\4\0\13\7\5\0\53\6\37\7\4\0"+
    "\2\6\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7"+
    "\1\0\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6"+
    "\1\7\36\6\33\7\2\0\131\6\13\7\1\6\16\0\12\7\41\6"+
    "\11\7\2\6\4\0\1\6\5\0\26\6\4\7\1\6\11\7\1\6"+
    "\3\7\1\6\5\7\22\0\31\6\3\7\104\0\1\6\1\0\13\6"+
    "\67\0\33\7\1\0\4\7\66\6\3\7\1\6\22\7\1\6\7\7"+
    "\12\6\2\7\2\0\12\7\1\0\7\6\1\0\7\6\1\0\3\7"+
    "\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\1\6"+
    "\3\0\4\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7"+
    "\1\6\10\0\1\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7"+
    "\4\6\7\0\1\6\5\0\3\7\1\0\6\6\4\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0"+
    "\1\7\1\0\5\7\4\0\2\7\2\0\3\7\3\0\1\7\7\0"+
    "\4\6\1\0\1\6\7\0\14\7\3\6\1\7\13\0\3\7\1\0"+
    "\11\6\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\2\0\1\7\1\6\10\7\1\0\3\7\1\0\3\7\2\0"+
    "\1\6\17\0\2\6\2\7\2\0\12\7\1\0\1\6\17\0\3\7"+
    "\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\5\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7"+
    "\10\0\2\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7\1\0"+
    "\1\6\20\0\1\7\1\6\1\0\6\6\3\0\3\6\1\0\4\6"+
    "\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6"+
    "\3\0\14\6\4\0\5\7\3\0\3\7\1\0\4\7\2\0\1\6"+
    "\6\0\1\7\16\0\12\7\11\0\1\6\7\0\3\7\1\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\7\0\2\7\1\0\2\6\6\0"+
    "\2\6\2\7\2\0\12\7\22\0\2\7\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\7\1\6\7\7"+
    "\1\0\3\7\1\0\4\7\7\0\2\7\7\0\1\6\1\0\2\6"+
    "\2\7\2\0\12\7\1\0\2\6\17\0\2\7\1\0\10\6\1\0"+
    "\3\6\1\0\51\6\2\0\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\1\6\10\0\1\7\10\0\2\6\2\7\2\0\12\7\12\0\6\6"+
    "\2\0\2\7\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6"+
    "\2\0\7\6\3\0\1\7\4\0\6\7\1\0\1\7\1\0\10\7"+
    "\22\0\2\7\15\0\60\6\1\7\2\6\7\7\4\0\10\6\10\7"+
    "\1\0\12\7\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\2\0\1\6\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6"+
    "\1\0\1\6\2\0\2\6\1\0\4\6\1\7\2\6\6\7\1\0"+
    "\2\7\1\6\2\0\5\6\1\0\1\6\1\0\6\7\2\0\12\7"+
    "\2\0\4\6\40\0\1\6\27\0\2\7\6\0\12\7\13\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\10\6\1\0\44\6\4\0"+
    "\24\7\1\0\2\7\5\6\13\7\1\0\44\7\11\0\1\7\71\0"+
    "\53\6\24\7\1\6\12\7\6\0\6\6\4\7\4\6\3\7\1\6"+
    "\3\7\2\6\7\7\3\6\4\7\15\6\14\7\1\6\17\7\2\0"+
    "\46\6\1\0\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0"+
    "\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0"+
    "\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6\2\0"+
    "\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0"+
    "\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7"+
    "\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6"+
    "\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7"+
    "\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6"+
    "\1\7\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0\14\7"+
    "\12\0\12\7\36\6\2\0\5\6\13\0\54\6\4\0\21\7\7\6"+
    "\2\7\6\0\12\7\46\0\27\6\5\7\4\0\65\6\12\7\1\0"+
    "\35\7\2\0\13\7\6\0\12\7\15\0\1\6\130\0\5\7\57\6"+
    "\21\7\7\6\4\0\12\7\21\0\11\7\14\0\3\7\36\6\15\7"+
    "\2\6\12\7\54\6\16\7\14\0\44\6\24\7\10\0\12\7\3\0"+
    "\3\6\12\7\44\6\122\0\3\7\1\0\25\7\4\6\1\7\4\6"+
    "\3\7\2\6\11\0\300\6\47\7\25\0\4\7\u0116\6\2\0\6\6"+
    "\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0\1\6"+
    "\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0\15\6"+
    "\5\0\3\6\1\0\7\6\16\0\5\7\30\0\1\101\1\101\5\7"+
    "\20\0\2\6\23\0\1\6\13\0\5\7\5\0\6\7\1\0\1\6"+
    "\15\0\1\6\20\0\15\6\3\0\33\6\25\0\15\7\4\0\1\7"+
    "\3\0\14\7\21\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6"+
    "\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6"+
    "\1\0\13\6\2\0\4\6\5\0\5\6\4\0\1\6\21\0\51\6"+
    "\u0a77\0\57\6\1\0\57\6\1\0\205\6\6\0\4\6\3\7\2\6"+
    "\14\0\46\6\1\0\1\6\5\0\1\6\2\0\70\6\7\0\1\6"+
    "\17\0\1\7\27\6\11\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7\1\0\5\6"+
    "\2\0\5\6\4\0\126\6\2\0\2\7\2\0\3\6\1\0\132\6"+
    "\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0\20\6"+
    "\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0\56\6\2\0\u010d\6"+
    "\3\0\20\6\12\7\2\6\24\0\57\6\1\7\4\0\12\7\1\0"+
    "\31\6\7\0\1\7\120\6\2\7\45\0\11\6\2\0\147\6\2\0"+
    "\4\6\1\0\4\6\14\0\13\6\115\0\12\6\1\7\3\6\1\7"+
    "\4\6\1\7\27\6\5\7\20\0\1\6\7\0\64\6\14\0\2\7"+
    "\62\6\21\7\13\0\12\7\6\0\22\7\6\6\3\0\1\6\4\0"+
    "\12\7\34\6\10\7\2\0\27\6\15\7\14\0\35\6\3\0\4\7"+
    "\57\6\16\7\16\0\1\6\12\7\46\0\51\6\16\7\11\0\3\6"+
    "\1\7\10\6\2\7\2\0\12\7\6\0\27\6\3\0\1\6\1\7"+
    "\4\0\60\6\1\7\1\6\3\7\2\6\2\7\5\6\2\7\1\6"+
    "\1\7\1\6\30\0\3\6\2\0\13\6\5\7\2\0\3\6\2\7"+
    "\12\0\6\6\2\0\6\6\2\0\6\6\11\0\7\6\1\0\7\6"+
    "\221\0\43\6\10\7\1\0\2\7\2\0\12\7\6\0\u2ba4\6\14\0"+
    "\27\6\4\0\61\6\u2104\0\u016e\6\2\0\152\6\46\0\7\6\14\0"+
    "\5\6\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0"+
    "\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0"+
    "\100\6\2\0\66\6\50\0\15\6\3\0\20\7\20\0\7\7\14\0"+
    "\2\6\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0"+
    "\1\7\4\0\1\6\13\0\12\7\7\0\32\6\4\0\1\6\1\0"+
    "\32\6\13\0\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0"+
    "\3\6\3\0\2\6\3\0\2\6\22\0\3\7\4\0\14\6\1\0"+
    "\32\6\1\0\23\6\1\0\2\6\1\0\17\6\2\0\16\6\42\0"+
    "\173\6\105\0\65\6\210\0\1\7\202\0\35\6\3\0\61\6\57\0"+
    "\37\6\21\0\33\6\65\0\36\6\2\0\44\6\4\0\10\6\1\0"+
    "\5\6\52\0\236\6\2\0\12\7\u0356\0\6\6\2\0\1\6\1\0"+
    "\54\6\1\0\2\6\3\0\1\6\2\0\27\6\252\0\26\6\12\0"+
    "\32\6\106\0\70\6\6\0\2\6\100\0\1\6\3\7\1\0\2\7"+
    "\5\0\4\7\4\6\1\0\3\6\1\0\33\6\4\0\3\7\4\0"+
    "\1\7\40\0\35\6\203\0\66\6\12\0\26\6\12\0\23\6\215\0"+
    "\111\6\u03b7\0\3\7\65\6\17\7\37\0\12\7\20\0\3\7\55\6"+
    "\13\7\2\0\1\7\22\0\31\6\7\0\12\7\6\0\3\7\44\6"+
    "\16\7\1\0\12\7\100\0\3\7\60\6\16\7\4\6\13\0\12\7"+
    "\u04a6\0\53\6\15\7\10\0\12\7\u0936\0\u036f\6\221\0\143\6\u0b9d\0"+
    "\u042f\6\u33d1\0\u0239\6\u04c7\0\105\6\13\0\1\6\56\7\20\0\4\7"+
    "\15\6\u4060\0\2\6\u2163\0\5\7\3\0\26\7\2\0\7\7\36\0"+
    "\4\7\224\0\3\7\u01bb\0\125\6\1\0\107\6\1\0\2\6\2\0"+
    "\1\6\2\0\2\6\2\0\4\6\1\0\14\6\1\0\1\6\1\0"+
    "\7\6\1\0\101\6\1\0\4\6\2\0\10\6\1\0\7\6\1\0"+
    "\34\6\1\0\4\6\1\0\5\6\1\0\1\6\3\0\7\6\1\0"+
    "\u0154\6\2\0\31\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0"+
    "\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6\1\0"+
    "\31\6\1\0\10\6\2\0\62\7\u1600\0\4\6\1\0\33\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\6\1\0\12\6\1\0\4\6\1\0"+
    "\1\6\1\0\1\6\6\0\1\6\4\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\1\0\2\6\1\0\1\6\2\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\2\6\1\0"+
    "\1\6\2\0\4\6\1\0\7\6\1\0\4\6\1\0\4\6\1\0"+
    "\1\6\1\0\12\6\1\0\21\6\5\0\3\6\1\0\5\6\1\0"+
    "\21\6\u1144\0\ua6d7\6\51\0\u1035\6\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\7\36\0\140\7\200\0\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\1"+
    "\1\5\1\7\1\10\1\11\6\5\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\1\1\27\1\30\1\31\2\32\1\33"+
    "\2\1\2\34\1\1\1\2\1\0\1\35\1\36\1\0"+
    "\2\35\1\36\1\0\1\5\1\0\5\5\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\2\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\12\46\1\0\2\61\1\35\1\36\1\0\1\5\1\0"+
    "\5\5\1\47\1\0\1\62\1\0\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\61\1\35\1\73"+
    "\1\0\5\5\1\61\1\35\1\0\3\5\1\74\1\75"+
    "\1\61\1\35\1\0\1\76\1\77\1\5\1\61\1\35"+
    "\1\0\1\100\1\61\1\35\1\0\1\61\1\35\1\0"+
    "\1\61\1\35\1\0\1\35\1\101\5\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\314\0\u0154\0\314"+
    "\0\u0198\0\u01dc\0\u0220\0\u0264\0\u02a8\0\u02ec\0\314\0\314"+
    "\0\u0330\0\u0374\0\u03b8\0\u03fc\0\u0440\0\u0484\0\314\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\314\0\u04c8"+
    "\0\u050c\0\u0550\0\u0594\0\u05d8\0\u061c\0\314\0\314\0\u0660"+
    "\0\u06a4\0\314\0\314\0\u06e8\0\u072c\0\u0770\0\314\0\u07b4"+
    "\0\u07f8\0\u083c\0\u0880\0\u08c4\0\u0908\0\u094c\0\u0990\0\u09d4"+
    "\0\u0a18\0\u0a5c\0\u0aa0\0\u0ae4\0\u0b28\0\u0b6c\0\u0bb0\0\u0bf4"+
    "\0\u0198\0\314\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\u0c38\0\u0c7c\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\u0cc0\0\u0d04\0\u0d48\0\u0d8c\0\u0dd0"+
    "\0\u0e14\0\u0e58\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68\0\u0908\0\u0fac"+
    "\0\u0ff0\0\u1034\0\u1034\0\u1078\0\u10bc\0\u1100\0\u1144\0\u1188"+
    "\0\u11cc\0\u1210\0\314\0\u0d04\0\314\0\u1254\0\314\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\u1298\0\u12dc"+
    "\0\u0198\0\u1320\0\u1364\0\u13a8\0\u13ec\0\u1430\0\u1474\0\u14b8"+
    "\0\u14fc\0\u1540\0\u1584\0\u15c8\0\u160c\0\u0198\0\u0198\0\u1650"+
    "\0\u1694\0\u16d8\0\u0198\0\u0198\0\u171c\0\u1760\0\u17a4\0\u17e8"+
    "\0\u0198\0\u182c\0\u1870\0\u18b4\0\u18f8\0\u193c\0\u1980\0\314"+
    "\0\u19c4\0\u1a08\0\u1a4c\0\314\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c"+
    "\0\u08c4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\2\11\2\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\4\1\21\1\22\5\11\1\23\4\11\1\24\3\11"+
    "\1\25\1\11\1\26\2\11\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\6\13\1\11\1\4"+
    "\1\6\1\4\1\50\1\51\1\52\16\50\1\53\1\50"+
    "\1\54\60\50\1\55\1\56\1\57\17\55\1\4\1\60"+
    "\60\55\106\0\1\6\105\0\1\61\1\62\104\0\10\11"+
    "\1\0\1\11\4\0\25\11\21\0\7\11\2\0\1\11"+
    "\10\0\1\63\1\64\1\65\1\0\1\66\1\67\1\70"+
    "\1\71\5\0\1\71\44\0\2\66\2\67\1\64\1\67"+
    "\14\0\2\13\2\0\2\13\1\70\1\71\5\0\1\71"+
    "\44\0\6\13\14\0\2\70\2\0\2\70\54\0\6\70"+
    "\12\0\10\11\1\0\1\11\4\0\15\11\1\72\7\11"+
    "\21\0\7\11\2\0\1\11\72\0\1\73\17\0\10\11"+
    "\1\0\1\11\4\0\1\11\1\74\23\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\11\4\0\6\11"+
    "\1\75\16\11\21\0\7\11\2\0\1\11\6\0\10\11"+
    "\1\0\1\11\4\0\10\11\1\76\14\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\11\4\0\15\11"+
    "\1\77\7\11\21\0\7\11\2\0\1\11\6\0\10\11"+
    "\1\0\1\11\4\0\21\11\1\100\3\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\11\4\0\23\11"+
    "\1\101\1\11\21\0\7\11\2\0\1\11\62\0\1\102"+
    "\103\0\1\103\103\0\1\104\103\0\1\105\107\0\1\106"+
    "\104\0\1\107\14\0\1\50\2\0\16\50\1\0\1\50"+
    "\1\0\60\50\2\0\1\52\101\0\1\110\2\0\5\110"+
    "\1\111\3\110\1\111\1\112\3\110\1\113\1\114\1\115"+
    "\10\110\1\116\1\117\1\110\1\120\7\110\1\121\22\110"+
    "\2\111\2\112\1\110\1\112\1\122\25\0\1\123\63\0"+
    "\1\57\101\0\1\110\2\0\5\110\1\124\3\110\1\124"+
    "\1\125\3\110\1\126\1\127\1\130\10\110\1\131\1\132"+
    "\1\110\1\133\7\110\1\134\22\110\2\124\2\125\1\110"+
    "\1\125\1\135\3\0\1\61\1\5\1\6\101\61\5\62"+
    "\1\136\76\62\10\0\1\63\1\64\2\0\1\66\1\67"+
    "\1\70\1\71\5\0\1\71\44\0\2\66\2\67\1\64"+
    "\1\67\14\0\2\64\2\0\2\64\1\70\1\71\5\0"+
    "\1\71\44\0\6\64\14\0\1\137\1\140\1\0\3\140"+
    "\1\0\1\140\4\0\3\140\1\0\1\140\7\0\1\140"+
    "\2\0\1\140\3\0\1\140\22\0\7\140\13\0\1\67"+
    "\1\64\2\0\2\67\1\70\1\71\5\0\1\71\44\0"+
    "\4\67\1\64\1\67\14\0\1\141\1\64\2\0\2\141"+
    "\1\70\1\71\5\0\1\71\44\0\4\141\1\64\1\141"+
    "\14\0\2\70\2\0\2\70\1\0\1\71\5\0\1\71"+
    "\44\0\6\70\14\0\2\142\2\0\2\142\2\0\1\143"+
    "\47\0\1\143\1\0\6\142\12\0\10\11\1\0\1\11"+
    "\4\0\24\11\1\144\21\0\7\11\2\0\1\11\73\0"+
    "\1\145\16\0\10\11\1\0\1\11\4\0\2\11\1\146"+
    "\22\11\21\0\7\11\2\0\1\11\6\0\10\11\1\0"+
    "\1\11\4\0\1\147\24\11\21\0\7\11\2\0\1\11"+
    "\6\0\10\11\1\0\1\11\4\0\11\11\1\150\13\11"+
    "\21\0\7\11\2\0\1\11\6\0\10\11\1\0\1\11"+
    "\4\0\16\11\1\151\6\11\21\0\7\11\2\0\1\11"+
    "\6\0\10\11\1\0\1\11\4\0\22\11\1\152\2\11"+
    "\21\0\7\11\2\0\1\11\10\0\1\112\3\0\2\112"+
    "\54\0\4\112\1\0\1\112\14\0\1\153\3\0\2\153"+
    "\54\0\4\153\1\0\1\153\14\0\1\154\3\0\2\154"+
    "\4\0\1\155\47\0\4\154\1\0\1\154\14\0\1\156"+
    "\3\0\2\156\4\0\1\155\47\0\4\156\1\0\1\156"+
    "\26\0\1\157\103\0\1\160\103\0\1\161\103\0\1\162"+
    "\103\0\1\163\103\0\1\164\103\0\1\165\103\0\1\166"+
    "\61\0\4\62\1\6\1\136\76\62\10\0\2\167\1\0"+
    "\3\167\1\0\1\167\4\0\3\167\1\0\1\167\7\0"+
    "\1\167\2\0\1\167\3\0\1\167\22\0\7\167\13\0"+
    "\1\170\1\64\2\0\2\170\1\70\1\71\5\0\1\71"+
    "\44\0\4\170\1\64\1\170\14\0\2\142\2\0\2\142"+
    "\54\0\6\142\12\0\10\11\1\0\1\171\4\0\25\11"+
    "\21\0\7\11\2\0\1\11\74\0\1\172\15\0\10\11"+
    "\1\0\1\11\4\0\3\11\1\173\21\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\11\4\0\1\174"+
    "\24\11\21\0\7\11\2\0\1\11\6\0\10\11\1\0"+
    "\1\175\4\0\25\11\21\0\7\11\2\0\1\11\6\0"+
    "\10\11\1\0\1\11\4\0\17\11\1\176\5\11\21\0"+
    "\7\11\2\0\1\11\6\0\10\11\1\0\1\11\4\0"+
    "\15\11\1\177\7\11\21\0\7\11\2\0\1\11\22\0"+
    "\1\155\71\0\2\200\1\0\3\200\1\0\1\200\4\0"+
    "\3\200\1\0\1\200\7\0\1\200\2\0\1\200\3\0"+
    "\1\200\22\0\7\200\13\0\1\201\1\64\2\0\2\201"+
    "\1\70\1\71\5\0\1\71\44\0\4\201\1\64\1\201"+
    "\101\0\1\202\14\0\10\11\1\0\1\11\4\0\4\11"+
    "\1\203\20\11\21\0\7\11\2\0\1\11\6\0\10\11"+
    "\1\0\1\11\4\0\1\11\1\204\23\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\11\4\0\12\11"+
    "\1\205\12\11\21\0\7\11\2\0\1\11\6\0\10\11"+
    "\1\0\1\11\4\0\11\11\1\206\13\11\21\0\7\11"+
    "\2\0\1\11\6\0\10\11\1\0\1\207\4\0\25\11"+
    "\21\0\7\11\2\0\1\11\10\0\2\210\1\0\3\210"+
    "\1\0\1\210\4\0\3\210\1\0\1\210\7\0\1\210"+
    "\2\0\1\210\3\0\1\210\22\0\7\210\13\0\1\211"+
    "\1\64\2\0\2\211\1\70\1\71\5\0\1\71\44\0"+
    "\4\211\1\64\1\211\100\0\1\212\15\0\10\11\1\0"+
    "\1\11\4\0\5\11\1\213\17\11\21\0\7\11\2\0"+
    "\1\11\6\0\10\11\1\0\1\11\4\0\2\11\1\214"+
    "\22\11\21\0\7\11\2\0\1\11\6\0\10\11\1\0"+
    "\1\215\4\0\25\11\21\0\7\11\2\0\1\11\10\0"+
    "\2\216\1\0\3\216\1\0\1\216\4\0\3\216\1\0"+
    "\1\216\7\0\1\216\2\0\1\216\3\0\1\216\22\0"+
    "\7\216\13\0\1\217\1\64\2\0\2\217\1\70\1\71"+
    "\5\0\1\71\44\0\4\217\1\64\1\217\102\0\1\220"+
    "\13\0\10\11\1\0\1\11\4\0\13\11\1\221\11\11"+
    "\21\0\7\11\2\0\1\11\10\0\2\222\1\0\3\222"+
    "\1\0\1\222\4\0\3\222\1\0\1\222\7\0\1\222"+
    "\2\0\1\222\3\0\1\222\22\0\7\222\13\0\1\223"+
    "\1\64\2\0\2\223\1\70\1\71\5\0\1\71\44\0"+
    "\4\223\1\64\1\223\20\0\1\224\77\0\2\225\1\0"+
    "\3\225\1\0\1\225\4\0\3\225\1\0\1\225\7\0"+
    "\1\225\2\0\1\225\3\0\1\225\22\0\7\225\13\0"+
    "\1\226\1\64\2\0\2\226\1\70\1\71\5\0\1\71"+
    "\44\0\4\226\1\64\1\226\103\0\1\227\14\0\2\230"+
    "\1\0\3\230\1\0\1\230\4\0\3\230\1\0\1\230"+
    "\7\0\1\230\2\0\1\230\3\0\1\230\22\0\7\230"+
    "\13\0\1\231\1\64\2\0\2\231\1\70\1\71\5\0"+
    "\1\71\44\0\4\231\1\64\1\231\100\0\1\232\17\0"+
    "\1\233\1\64\2\0\2\233\1\70\1\71\5\0\1\71"+
    "\44\0\4\233\1\64\1\233\102\0\1\234\15\0\1\235"+
    "\1\64\2\0\2\235\1\70\1\71\5\0\1\71\44\0"+
    "\4\235\1\64\1\235\14\0\1\236\1\64\2\0\2\236"+
    "\1\70\1\71\5\0\1\71\44\0\4\236\1\64\1\236"+
    "\14\0\1\237\1\64\2\0\2\237\1\70\1\71\5\0"+
    "\1\71\44\0\4\237\1\64\1\237\14\0\1\240\1\64"+
    "\2\0\2\240\1\70\1\71\5\0\1\71\44\0\4\240"+
    "\1\64\1\240\14\0\1\241\1\64\2\0\2\241\1\70"+
    "\1\71\5\0\1\71\44\0\4\241\1\64\1\241\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7072];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\1\1\1\11\6\1\2\11"+
    "\6\1\11\11\6\1\2\11\2\1\2\11\3\1\1\11"+
    "\2\1\1\0\2\1\1\0\3\1\1\0\1\1\1\0"+
    "\6\1\7\11\2\1\11\11\12\1\1\0\4\1\1\0"+
    "\1\1\1\0\5\1\1\11\1\0\1\11\1\0\10\11"+
    "\3\1\1\0\7\1\1\0\7\1\1\0\5\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\11\1\1\1\0\1\1"+
    "\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder string = new StringBuilder();
  
  private Symbol symbol(int type) {
    return new JavaSymbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, value);
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2898) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
            }
          case 66: break;
          case 2: 
            { /* ignore */
            }
          case 67: break;
          case 3: 
            { return symbol(DIV);
            }
          case 68: break;
          case 4: 
            { return symbol(MULT);
            }
          case 69: break;
          case 5: 
            { return symbol(IDENTIFIER, yytext());
            }
          case 70: break;
          case 6: 
            { return symbol(INTEGER_LITERAL, new Integer(yytext()));
            }
          case 71: break;
          case 7: 
            { return symbol(MINUS);
            }
          case 72: break;
          case 8: 
            { yybegin(STRING); string.setLength(0);
            }
          case 73: break;
          case 9: 
            { yybegin(CHARLITERAL);
            }
          case 74: break;
          case 10: 
            { return symbol(LPAREN);
            }
          case 75: break;
          case 11: 
            { return symbol(RPAREN);
            }
          case 76: break;
          case 12: 
            { return symbol(LBRACE);
            }
          case 77: break;
          case 13: 
            { return symbol(RBRACE);
            }
          case 78: break;
          case 14: 
            { return symbol(LBRACK);
            }
          case 79: break;
          case 15: 
            { return symbol(RBRACK);
            }
          case 80: break;
          case 16: 
            { return symbol(SEMICOLON);
            }
          case 81: break;
          case 17: 
            { return symbol(COLON);
            }
          case 82: break;
          case 18: 
            { return symbol(COMMA);
            }
          case 83: break;
          case 19: 
            { return symbol(EQ);
            }
          case 84: break;
          case 20: 
            { return symbol(GT);
            }
          case 85: break;
          case 21: 
            { return symbol(LT);
            }
          case 86: break;
          case 22: 
            { return symbol(NOT);
            }
          case 87: break;
          case 23: 
            { return symbol(PLUS);
            }
          case 88: break;
          case 24: 
            { return symbol(MOD);
            }
          case 89: break;
          case 25: 
            { string.append( yytext() );
            }
          case 90: break;
          case 26: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 91: break;
          case 27: 
            { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
            }
          case 92: break;
          case 28: 
            { throw new RuntimeException("Unterminated character literal at end of line");
            }
          case 93: break;
          case 29: 
            { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(0, yylength(), 8)));
            }
          case 94: break;
          case 30: 
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
            }
          case 95: break;
          case 31: 
            { return symbol(IF);
            }
          case 96: break;
          case 32: 
            { return symbol(EQEQ);
            }
          case 97: break;
          case 33: 
            { return symbol(GTEQ);
            }
          case 98: break;
          case 34: 
            { return symbol(LTEQ);
            }
          case 99: break;
          case 35: 
            { return symbol(NOTEQ);
            }
          case 100: break;
          case 36: 
            { return symbol(ANDAND);
            }
          case 101: break;
          case 37: 
            { return symbol(OROR);
            }
          case 102: break;
          case 38: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 103: break;
          case 39: 
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
            }
          case 104: break;
          case 40: 
            { string.append( '\"' );
            }
          case 105: break;
          case 41: 
            { string.append( '\'' );
            }
          case 106: break;
          case 42: 
            { string.append( '\\' );
            }
          case 107: break;
          case 43: 
            { string.append( '\n' );
            }
          case 108: break;
          case 44: 
            { string.append( '\t' );
            }
          case 109: break;
          case 45: 
            { string.append( '\r' );
            }
          case 110: break;
          case 46: 
            { string.append( '\f' );
            }
          case 111: break;
          case 47: 
            { string.append( '\b' );
            }
          case 112: break;
          case 48: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yytext().charAt(0));
            }
          case 113: break;
          case 49: 
            { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(2, yylength(), 16)));
            }
          case 114: break;
          case 50: 
            { yybegin(YYINITIAL); 
			                              int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
			                            return symbol(CHARACTER_LITERAL, (char)val);
            }
          case 115: break;
          case 51: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\"');
            }
          case 116: break;
          case 52: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\'');
            }
          case 117: break;
          case 53: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\\');
            }
          case 118: break;
          case 54: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\n');
            }
          case 119: break;
          case 55: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\t');
            }
          case 120: break;
          case 56: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\r');
            }
          case 121: break;
          case 57: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\f');
            }
          case 122: break;
          case 58: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\b');
            }
          case 123: break;
          case 59: 
            { return symbol(ELSE);
            }
          case 124: break;
          case 60: 
            { return symbol(FLOAT);
            }
          case 125: break;
          case 61: 
            { return symbol(WHILE);
            }
          case 126: break;
          case 62: 
            { return symbol(DECVAR);
            }
          case 127: break;
          case 63: 
            { return symbol(ENDDEC);
            }
          case 128: break;
          case 64: 
            { return symbol(INTEGER);
            }
          case 129: break;
          case 65: 
            { return symbol(INTEGER_LITERAL, new Integer(Integer.MIN_VALUE));
            }
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
