
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 14 12:12:40 ART 2017
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 41;
  public static final int GTEQ = 34;
  public static final int MULT = 9;
  public static final int LTEQ = 33;
  public static final int ENDVAR = 3;
  public static final int LINE_TERMINATOR = 24;
  public static final int INTEGER = 4;
  public static final int LPAREN = 14;
  public static final int MINUS = 26;
  public static final int RPAREN = 15;
  public static final int OROR = 38;
  public static final int NOT = 28;
  public static final int SEMICOLON = 8;
  public static final int LT = 31;
  public static final int COMMA = 10;
  public static final int COMP = 27;
  public static final int ANDAND = 37;
  public static final int DIV = 29;
  public static final int PLUS = 25;
  public static final int IF = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQEQ = 35;
  public static final int MOD = 30;
  public static final int EQ = 13;
  public static final int LBRACK = 6;
  public static final int DECVAR = 2;
  public static final int COLON = 16;
  public static final int FLOATING_POINT_LITERAL = 40;
  public static final int LBRACE = 11;
  public static final int ELSE = 18;
  public static final int RBRACK = 7;
  public static final int WHILE = 20;
  public static final int FLOAT = 5;
  public static final int THEN = 19;
  public static final int RBRACE = 12;
  public static final int END = 22;
  public static final int GT = 32;
  public static final int PRINT = 23;
  public static final int DO = 21;
  public static final int NOTEQ = 36;
  public static final int IDENTIFIER = 42;
  public static final int INTEGER_LITERAL = 39;
}

