
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 05 10:52:06 ART 2017
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 39;
  public static final int GTEQ = 30;
  public static final int ENDDEC = 3;
  public static final int MULT = 10;
  public static final int CONST = 43;
  public static final int LTEQ = 29;
  public static final int STRICTFP = 42;
  public static final int INTEGER = 4;
  public static final int LPAREN = 15;
  public static final int MINUS = 22;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 37;
  public static final int OROR = 34;
  public static final int CHARACTER_LITERAL = 38;
  public static final int NOT = 24;
  public static final int SEMICOLON = 9;
  public static final int LT = 27;
  public static final int COMMA = 11;
  public static final int COMP = 23;
  public static final int DIV = 25;
  public static final int ANDAND = 33;
  public static final int PLUS = 21;
  public static final int NULL_LITERAL = 41;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int error = 1;
  public static final int EQEQ = 31;
  public static final int MOD = 26;
  public static final int EQ = 14;
  public static final int LBRACK = 7;
  public static final int DECVAR = 2;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 36;
  public static final int LBRACE = 12;
  public static final int ELSE = 19;
  public static final int RBRACK = 8;
  public static final int GOTO = 44;
  public static final int WHILE = 20;
  public static final int FLOAT = 5;
  public static final int RBRACE = 13;
  public static final int GT = 28;
  public static final int NOTEQ = 32;
  public static final int IDENTIFIER = 40;
  public static final int INTEGER_LITERAL = 35;
}

