
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 13 13:30:58 ART 2017
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POW = 34;
  public static final int STRING_LITERAL = 44;
  public static final int GTEQ = 38;
  public static final int SQRT = 28;
  public static final int MULT = 9;
  public static final int LTEQ = 37;
  public static final int ENDVAR = 3;
  public static final int INTEGER = 4;
  public static final int LPAREN = 14;
  public static final int MINUS = 30;
  public static final int RPAREN = 15;
  public static final int SEMICOLON = 8;
  public static final int LT = 35;
  public static final int COMMA = 10;
  public static final int COMP = 31;
  public static final int DIV = 32;
  public static final int PLUS = 29;
  public static final int ASSIGN = 13;
  public static final int IF = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQEQ = 39;
  public static final int COS = 27;
  public static final int MOD = 33;
  public static final int EQ = 41;
  public static final int LBRACK = 6;
  public static final int DECVAR = 2;
  public static final int TRUNC = 24;
  public static final int COLON = 16;
  public static final int FLOATING_POINT_LITERAL = 43;
  public static final int LBRACE = 11;
  public static final int ELSE = 18;
  public static final int PLUSTRUNC = 25;
  public static final int SIN = 26;
  public static final int RBRACK = 7;
  public static final int WHILE = 20;
  public static final int FLOAT = 5;
  public static final int THEN = 19;
  public static final int RBRACE = 12;
  public static final int END = 22;
  public static final int GT = 36;
  public static final int PRINT = 23;
  public static final int DO = 21;
  public static final int NOTEQ = 40;
  public static final int IDENTIFIER = 45;
  public static final int INTEGER_LITERAL = 42;
}

